FROM debian:buster-slim
RUN apt-get update && apt-get install -y \
    openssh-server



# RUN useradd -m -s /bin/bash kermit \
#     && echo "kermit:0n3_st3p_c10s3r" | chpasswd



#################################################################################
COPY solve /

#################################################################################
